# site settings
title: macroservices.de
subtitle: by Conciso.
email: macroservices@conciso.de
description: Warum es nicht um „entweder oder”,<br />sondern um „sowohl als auch” geht.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
company: Conciso GmbH
street_address: Pariser Bogen 7
city: Dortmund
zip_code: 44269
country:
phone: +49 231 5648 450

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url:
github_url: https://github.com/conciso
gitlab_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/conciso/
xing_url: https://www.xing.com/companies/conciso
twitter_url: https://twitter.com/ConcisoIT

# build settings
markdown: kramdown

sass:
  style: compressed
